15687 pay remove restx
bcgov/sbc-pay pull request #1234
Opened 2023-09-05 21:00 UTC by ochiu

*Issue #:*
https://github.com/bcgov/entity/issues/15687

*Description of changes:*
- remove restx from pay-api

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-pay license (Apache 2.0).

2023-09-06 22:44 UTC, Jxio commented on pay-api/src/pay_api/resources/ops.py
can ops.py move to ../v1/ ?

2023-09-06 22:58 UTC, ochiu commented on pay-api/src/pay_api/resources/ops.py
The ops endpoint is part of the /ops route and not under /api/v1, so I kept it out of the v1 folder as it is not specific to a version.

2023-09-08 14:36 UTC, seeker25 commented
Please move `git mv` to preserve the history of the files.

2023-09-08 14:36 UTC, seeker25 requested changes
Please use `git mv` to preserve the history of the files. This is more important in PAY than AUTH.

2023-09-08 14:50 UTC, seeker25 commented
After reviewing with Ody, `git mv` wasn't the issue. It's done in the commits

2023-09-08 15:35 UTC, seeker25 commented
Another thing to note we discovered: when moving these files - better not to Squash and merge as is

2023-09-11 22:44 UTC, seeker25 approved these changes

2023-09-11 22:44 UTC, merged