19513 - Add more error catching for csv feedback reconciliation
bcgov/sbc-pay pull request #1624
Opened 2024-07-17 19:40 UTC by Jxio

*Issue #:*
https://github.com/bcgov/entity/issues/19513
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-pay license (Apache 2.0).

2024-07-17 19:46 UTC, seeker25 reviewed
re-raise exception, so it stops the flow

2024-07-17 22:31 UTC, Jxio commented
it should catch other error like syncing credit records
![image](https://github.com/user-attachments/assets/bb971216-1000-4ce9-afcb-d48254c2e087)

2024-07-18 15:38 UTC, seeker25 commented on pay-queue/src/pay_queue/services/payment_reconciliations.py
> +        error_msg = f'Error creating payment records: {str(e)}'
re-raise the exception here

2024-07-18 15:39 UTC, seeker25 requested changes
edit, didn't see return

2024-07-18 15:39 UTC, seeker25 approved these changes

2024-07-18 15:42 UTC, merged